url: https://y7kim.github.io
baseurl: 

# Site settings
title: Uman by Renovatio
email: renovatio.uman@gmail.com
description: "An App for your help, in time of trouble. Uman for All Humans in Need."


# Team names, titles and social links
people:

- name: Nakul Agrawal
  pic: 1
  position: President @ Renovatio India
  social:
    - title: twitter
      url: https://www.twitter.com/livingnakul/
    - title: facebook
      url: https://www.facebook.com/rhythm.of.nakul/
    - title: linkedin
      url: https://www.linkedin.com/in/livingnakul/
    - title: instagram
      url: https://www.instagram.com/livingnakul/

- name: Shantanu Vishwanadha
  pic: 2
  position: Co-Founder @ ProCohat
  social:
    - title: twitter
      url: https://www.twitter.com/thecoderpanda/
    - title: facebook
      url: https://www.facebook.com/shantanu.vishwanadha/nk
    - title: linkedin
      url: https://www.linkedin.com/in/thecoderpanda/
    - title: instagram
      url:  https://www.instagram.com/thecoderpanda/

- name: Rajat Bhanarkar
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: https://twitter.com/irajatbhanarkar
    - title: facebook
      url: https://www.facebook.com/rajat.bhanarkar/
    - title: linkedin
      url: https://www.linkedin.com/in/rajat-bhanarkar-11a859176/
    - title: instagram
      url: https://www.instagram.com/____rajat________/

- name: Abhilash Karnale
  pic: 4
  position: Android Developer 
  social:
    # - title: twitter
      # url: #https://twitter.com/AnmolSingh1509/
    - title: facebook
      url: https://www.facebook.com/profile.php?id=100009221071077
    - title: linkedin
      url: https://www.linkedin.com/in/abhilash-karnale-0099821a9/
    - title: instagram
      url: https://www.instagram.com/avalon_ak24/

- name: Ansh Dhomne
  pic: 5
  position: Web Developer 
  social:
    # - title: twitter
      # url: https://www.twitter.com/AnmolSingh1509/
    - title: facebook
      url: https://www.facebook.com/anshdhomne.1
    - title: linkedin
      url: https://www.linkedin.com/in/ansh-dhomne/
    - title: instagram
      url: https://www.instagram.com/ansh.dhomne/

- name: Anmoldeep Singh Arora
  pic: 6
  position: Web Developer 
  social:
    - title: twitter
      url: https://www.twitter.com/AnmolSingh1509/
    - title: facebook
      url: https://www.facebook.com/Anmoldeep1509/
    - title: linkedin
      url: https://www.linkedin.com/in/anmoldeep1509/
    - title: instagram
      url: https://www.instagram.com/anmoldeep1509/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty