url: https://y7kim.github.io
baseurl: 

# Site settings
title: Uman by Renovatio
email: renovatio.uman@gmail.com
description: "An App for your help, in time of trouble. Uman for All Humans in Need."


# Team names, titles and social links
people:

- name: Nakul Agrawal
  pic: 1
  position: President @ Renovatio India
  social:
    - title: twitter
      url: https://twitter.com/livingnakul/
    - title: facebook
      url: https://www.facebook.com/rhythm.of.nakul/
    - title: linkedin
      url: https://www.linkedin.com/in/livingnakul/

- name: Shantanu Vishwanadha
  pic: 2
  position: Co-Founder @ ProCohat
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/thecoderpanda/

- name: Rajat Bhanarkar
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- name: Abhilash Karnale
  pic: 3

- name: Ansh Dhomne
  pic: 3

- name: Anmoldeep Singh Arora
  pic: 6

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
# markdown: kramdown
# permalink: pretty